### PR TITLE
feat: 0.6.0 Bee

### PR DESCRIPTION
**Pull request by nugaon**
This PR builds up the environment for the new Postage Stamp feature of Bee.

All Bee nodes will connect to the deployed Postage Stamp and Price Oracle contracts.

Until the 0.6.0 Bee release, it is going to pull the `latest` image from `ethersphere/bee`, so if you want to build it again with a newer commit which's Docker image was pushed as `latest` as well, you have to remove your pulled latest bee image with `docker image rm ethersphere/bee:latest` and download it again.

### CODE REVIEW

**Comment by nugaon** [comment]
I built the images, and for commit [631c8d8](https://github.com/ethersphere/bee/commit/631c8d8a01ae3b528cc79a6c664d97b3ef14cbe5) I've got an inifinite-loop like behaviour on bee-starts
Screenshot from 2021-04-29 18-26-10

Does someone have the same problem?

**Comment by nugaon** [comment]
> I built the image against their latest docker image (digest 228353c8eacc94c2afd3172f7e4bef8b70a24106c38fa6e43635ab6f168bb89a, last master commit [631c8d8](https://github.com/ethersphere/bee/commit/631c8d8a01ae3b528cc79a6c664d97b3ef14cbe5))

But as I see on the [Docker site](https://hub.docker.com/layers/ethersphere/bee/latest/images/sha256-228353c8eacc94c2afd3172f7e4bef8b70a24106c38fa6e43635ab6f168bb89a?context=explore) the image was pushed one hour later than the referred commit.

**Comment by AuHau** [comment]
I have tried to run your setup and I am running into same issue like you do 😳 Maybe lets reach out to the Bee team regarding what could be wrong?

**Review by AuHau — APPROVED** [review]
LGTM!

**Review by vojtechsimetka — APPROVED** [review]
LGTM and works well

**Pull request merged**
