### PR TITLE
chore: blockchain 1.1.1

### PR DESCRIPTION
**Pull request by nugaon**
New [simple swap factory binary update](https://github.com/ethersphere/docker-setup-contracts/pull/3/files#diff-30883d1df2fc62f59d66255a70dc05f60d3d4ef4d3957e6e3e38e62f6e471bd0R15) happened and Bee started to use from [this commit](https://github.com/ethersphere/bee/commit/5a01238318fcc5410fcbf8f4557d420ca8fddc36).

According to that, Bee Factory will release the new version of its blockchain image with this PR: 1.1.1.

### CODE REVIEW

**Comment by nugaon** [comment]
I already built the images for this setup that you can pull with `export BEE_VERSION=0.6.0-c37b31d-dirty` and `export BLOCKCHAIN_VERSION=1.1.1`

**Review by vojtechsimetka — APPROVED** [review]

**Comment by nugaon** [comment]
Unfortunately with the Bee version `0.6.0-c37b31d-dirty` the new factory does not work, we will see in a newer version.

**Comment by nugaon** [comment]
this new factory will be available after commit [5a01238318fcc5410fcbf8f4557d420ca8fddc36](https://github.com/ethersphere/bee/commit/5a01238318fcc5410fcbf8f4557d420ca8fddc36) but it is not available on [the official Docker site](https://hub.docker.com/layers/ethersphere/bee/latest/images/sha256-84884699e87602d2b1392be76513fdc8607b93153d3b3cf829a3eb9f3db62325?context=explore) yet.

**Comment by nugaon** [comment]
against [0.6.0-c1e87ce-dirty](https://github.com/ethersphere/bee-factory/packages/769580?version=0.6.0-c1e87ce-dirty) build it works!

**Review by AuHau — APPROVED** [review]

**Pull request merged**
